Repository project-codeflare/instascale, pull requests merged in 2023-08, with the labels that each got.

#119 Upgrade to MCAD v1.33.0
  controllers/appWrapper_controller_test.go
  controllers/appwrapper_controller.go
  go.mod
  go.sum
Labels: lgtm, approved

#121 Upgrade MCAD to latest version
  .github/workflows/go.yml
  .github/workflows/instascale-release.yml
  Dockerfile
  README.md
  go.mod
  go.sum
Labels: lgtm, approved

#124 Build and publish dev InstaScale image for every commit
  .github/workflows/operator-image.yml
Labels: lgtm, approved

#125 Release workflow opens PR with changes
  .github/workflows/instascale-release.yml
Labels: lgtm, approved

#85 perf: add liveness and readiness probes to deployments
  README.md
  config/manager/manager.yaml
  config/rbac/role.yaml
  deployment/deployment.yaml
  deployment/instascale-clusterrole.yaml
  deployment/instascale-clusterrolebinding.yaml
  deployment/instascale-configmap.yaml
  deployment/instascale-sa.yaml
Labels: approved

#130 Update go.mod and go.sum to MCAD v1.34.0
  go.mod
  go.sum
Labels: lgtm, approved

#128 Automatically label issues as needing triage and add them to project board
  .github/workflows/auto-add-issues.yml
Labels: lgtm
